package goutils

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"maps"
	"net/http"
)

var (
	// ErrInvalidHTTPScheme represents an invalid http(s) scheme error.
	ErrInvalidHTTPScheme = errors.New("invalid http(s) scheme")
	// ErrInvalidSlug represents an invalid slug error.
	ErrInvalidSlug = errors.New("invalid slug")
	// ErrMalformedJSON occurs when the JSON syntax or value is malformed.
	ErrMalformedJSON = errors.New("malformed JSON")
)

// CatchWarnErrorFunc catches the closer function and prints error with the WARN level.
func CatchWarnErrorFunc(fn func() error) {
	err := fn()
	if err != nil {
		slog.Warn(err.Error())
	}
}

// CatchWarnContextErrorFunc catches the closer function with context and prints error with the WARN level.
func CatchWarnContextErrorFunc(fn func(ctx context.Context) error) {
	err := fn(context.TODO())
	if err != nil {
		slog.Warn(err.Error())
	}
}

// RFC9457Error is the data structure of an HTTP error
// that follows the [RFC 9457] specification.
// The schema is inspired by [Swagger API] specification.
//
// [RFC 9457]: https://www.rfc-editor.org/rfc/rfc9457.html
// [Swagger API]: https://swagger.io/blog/problem-details-rfc9457-api-error-handling/
type RFC9457Error struct {
	// A URI reference that identifies the problem type.
	Type string `json:"type,omitempty"`
	// The HTTP status code generated by the origin server for this occurrence of the problem.
	Status int `json:"status,omitempty"`
	// A short, human-readable summary of the problem type.
	Title string `json:"title,omitempty"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.
	// It may or may not yield further information if dereferenced.
	Instance string `json:"instance,omitempty"`
	// An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry.
	Code string `json:"code,omitempty"`
	// An array of error details to accompany a problem details response.
	Errors []ErrorDetail `json:"errors,omitempty"`
}

// NewRFC9457Error creates an RFC9457Error instance with status.
func NewRFC9457Error(httpStatus int, detail string) RFC9457Error {
	return RFC9457Error{
		Type:   "about:blank",
		Status: httpStatus,
		Title:  http.StatusText(httpStatus),
		Detail: detail,
	}
}

// ErrorDetail is an object to provide explicit details on a problem towards an API consumer.
type ErrorDetail struct {
	// A granular description on the specific error related to a body property, query parameter, path parameters, and/or header.
	Detail string `json:"detail"`
	// A JSON Pointer to a specific request body property that is the source of error.
	Pointer string `json:"pointer,omitempty"`
	// The name of the query or path parameter that is the source of error.
	Parameter string `json:"parameter,omitempty"`
	// The name of the header that is the source of error.
	Header string `json:"header,omitempty"`
	// A string containing additional provider specific codes to identify the error context.
	Code string `json:"code,omitempty"`
}

// NewAlreadyExistsError creates an error that occurs when the resource being created is found to already exist on the server.
func NewAlreadyExistsError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/already-exists",
		Title:  "Already exists",
		Detail: "The resource being created already exists.",
		Status: http.StatusConflict,
		Code:   "409-01",
		Errors: errors,
	}
}

// NewServiceUnavailableError creates an error that occurs when the service requested is currently unavailable and the server is not ready to handle the request.
// Your client application did everything correct. Unfortunately our API is currently unavailable.
func NewServiceUnavailableError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "about:blank",
		Title:  "Service Unavailable",
		Detail: "The service is currently unavailable.",
		Status: http.StatusServiceUnavailable,
		Code:   "503-01",
		Errors: errors,
	}
}

// NewLicenseCancelledError creates an error that occurs when the license associated with the client has been cancelled thus rendering the service unavailable.
func NewLicenseCancelledError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/license-cancelled",
		Title:  "License Cancelled",
		Detail: "The service is unavailable as the license associated with your client or organization has been cancelled. Please contact your account manager or representative.",
		Status: http.StatusServiceUnavailable,
		Code:   "503-02",
		Errors: errors,
	}
}

// NewLicenseExpiredError creates an error that occurs when the license associated with the client has expired thus rendering the service unavailable.
func NewLicenseExpiredError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/license-expired",
		Title:  "License Expired",
		Detail: "The service is unavailable as the license associated with your client or organization has expired. Please contact your account manager or representative.",
		Status: http.StatusServiceUnavailable,
		Code:   "503-03",
		Errors: errors,
	}
}

// NewNotFoundError creates an error that occurs when the requested resource could not be found.
// Your client application tried to access a resource that does not exist (or could not be found).
// Please review how your users initiated such a request.
func NewNotFoundError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "about:blank",
		Title:  "Not Found",
		Detail: "The requested resource was not found.",
		Status: http.StatusNotFound,
		Code:   "404-01",
		Errors: errors,
	}
}

// NewUnauthorizedError creates an error that occurs when the request lacks valid authentication credentials.
// Your client application tried to access a resource without providing a valid access token or authentication information.
// Please ensure that your requests include the necessary authentication credentials.
func NewUnauthorizedError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "about:blank",
		Title:  "Unauthorized",
		Detail: "Access token not set or invalid, and the requested resource could not be returned.",
		Status: http.StatusUnauthorized,
		Code:   "401-01",
		Errors: errors,
	}
}

// NewForbiddenError creates an error that occurs when the requested resource
// (and/or operation combination) is not authorized for the requesting client (and or authorization context).
// Your client application tried to perform an operation on a resource that
// it’s not authorized to perform in the given context.
func NewForbiddenError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "about:blank",
		Title:  "Forbidden",
		Detail: "The resource could not be returned as the requestor is not authorized.",
		Status: http.StatusForbidden,
		Code:   "403-01",
		Errors: errors,
	}
}

// NewBadRequestError creates an error that occurs when the server cannot or will not process the request
// due to something that is perceived to be a client error
// (for example, malformed request syntax, invalid request message framing, or deceptive request routing).
// Your client application initiated a request that is malformed.
// Please review your client request against the defined semantics for the API.
func NewBadRequestError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "about:blank",
		Title:  "Bad Request",
		Detail: "The request is invalid or malformed.",
		Status: http.StatusBadRequest,
		Code:   "400-01",
		Errors: errors,
	}
}

// NewServerError creates an error that occurs when the server encounters an unexpected condition that prevents it from fulfilling the request.
// Your client application did everything correct. Unfortunately our API encountered a condition that resulted in this problem.
func NewServerError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "about:blank",
		Title:  "Server Error",
		Detail: "The server encountered an unexpected error.",
		Status: http.StatusInternalServerError,
		Code:   "500-01",
		Errors: errors,
	}
}

// NewMissingRequestHeaderError occurs when the request sent to the API is missing an expected request header.
func NewMissingRequestHeaderError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/missing-request-header",
		Title:  "Missing request header",
		Detail: "The request is missing an expected HTTP request header.",
		Status: http.StatusBadRequest,
		Code:   "400-02",
		Errors: errors,
	}
}

// NewMissingRequestParameterError occurs when the request sent to the API is missing a query or path parameter.
func NewMissingRequestParameterError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/missing-request-parameter",
		Title:  "Missing request parameter",
		Detail: "The request is missing an expected query or path parameter.",
		Status: http.StatusBadRequest,
		Code:   "400-03",
		Errors: errors,
	}
}

// NewInvalidBodyPropertyFormatError occurs when the request body contains a malformed property.
func NewInvalidBodyPropertyFormatError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/invalid-body-property-format",
		Title:  "Invalid Body Property Format",
		Detail: "The request body contains a malformed property.",
		Status: http.StatusBadRequest,
		Code:   "400-04",
		Errors: errors,
	}
}

// NewInvalidRequestParameterFormatError occurs when the request contains a malformed query or path parameter.
// Your client issued a request that contained a malformed query or path parameter.
// Please review your request parameters and compare against the shared API definition.
// Consider validating your parameters published schema prior to sending to the server.
func NewInvalidRequestParameterFormatError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/invalid-request-parameter-format",
		Title:  "Invalid Request Parameter Format",
		Detail: "The request contains a malformed query parameter.",
		Status: http.StatusBadRequest,
		Code:   "400-05",
		Errors: errors,
	}
}

// NewInvalidRequestHeaderFormatError occurs when the request contains a malformed request header.
// Your client issued a request that contained a malformed request header.
// Please review your request parameters and compare against the shared API definition when applicable.
// Consider validating your headers against the published schema or API definition metadata prior to sending to the server.
func NewInvalidRequestHeaderFormatError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/invalid-request-header-format",
		Title:  "Invalid Request Header Format",
		Detail: "The request contains a malformed request header parameter.",
		Status: http.StatusBadRequest,
		Code:   "400-06",
		Errors: errors,
	}
}

// NewInvalidBodyPropertyValueError occurs when the request body contains an invalid property value.
func NewInvalidBodyPropertyValueError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/invalid-body-property-value",
		Title:  "Invalid Body Property Value",
		Detail: "The request body contains an invalid body property value.",
		Status: http.StatusBadRequest,
		Code:   "400-07",
		Errors: errors,
	}
}

// NewInvalidRequestParameterValueError occurs when the request contains an invalid query or path parameter value.
func NewInvalidRequestParameterValueError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/invalid-request-parameter-value",
		Title:  "Invalid Request Parameter Value",
		Detail: "The request contains an invalid request parameter value.",
		Status: http.StatusBadRequest,
		Code:   "400-08",
		Errors: errors,
	}
}

// NewMissingBodyPropertyError creates a missing body property error.
// This problem occurs when the request sent to the API is missing an expected body property.
func NewMissingBodyPropertyError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/missing-body-property",
		Title:  "Missing body property",
		Detail: "The request is missing an expected body property.",
		Status: http.StatusBadRequest,
		Code:   "400-09",
		Errors: errors,
	}
}

// NewBusinessRuleViolationError occurs when the request is deemed unprocessable.
// Your client issued a request that failed business rule validation.
// Please review your request to determine if you can remain within appropriate business rules.
// Consider validating your request against available metadata (e.g. schemas) prior to sending to the server.
func NewBusinessRuleViolationError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/business-rule-violation",
		Title:  "Business Rule Violation",
		Detail: "The request body is invalid and not meeting business rules.",
		Status: http.StatusUnprocessableEntity,
		Code:   "422-01",
		Errors: errors,
	}
}

// NewValidationError occurs when the request is deemed unprocessable.
func NewValidationError(errors ...ErrorDetail) RFC9457Error {
	return RFC9457Error{
		Type:   "https://problems-registry.smartbear.com/validation-error",
		Title:  "Validation Error",
		Detail: "The request is not valid.",
		Status: http.StatusUnprocessableEntity,
		Code:   "422-02",
		Errors: errors,
	}
}

// Error implements the error interface for RFC9457Error.
func (e RFC9457Error) Error() string {
	return fmt.Sprintf("%s, type=%s, detail=%s, status=%d, instance=%s, errors=%v",
		e.Title, e.Type, e.Detail, e.Status, e.Instance, e.Errors)
}

// RFC9457ErrorWithExtensions is the data structure of an HTTP error with extensions.
// that follows the [RFC 9457] specification.
// The schema is inspired by [Swagger API] specification.
//
// [RFC 9457]: https://www.rfc-editor.org/rfc/rfc9457.html
// [Swagger API]: https://swagger.io/blog/problem-details-rfc9457-api-error-handling/
type RFC9457ErrorWithExtensions struct { //nolint:errname
	RFC9457Error

	// Additional members that are specific to that problem type.
	Extensions map[string]any
}

// NewRFC9457ErrorWithExtensions creates a new RFC 9457 error with extensions.
func NewRFC9457ErrorWithExtensions(
	err RFC9457Error,
	extensions map[string]any,
) RFC9457ErrorWithExtensions {
	return RFC9457ErrorWithExtensions{
		RFC9457Error: err,
		Extensions:   extensions,
	}
}

// MarshalJSON implements the json.Marshaler interface.
func (e RFC9457ErrorWithExtensions) MarshalJSON() ([]byte, error) {
	if len(e.Extensions) == 0 {
		return json.Marshal(e.RFC9457Error)
	}

	result := maps.Clone(e.Extensions)

	if e.Type != "" {
		result["type"] = e.Type
	}

	if e.Status > 0 {
		result["status"] = e.Status
	}

	if e.Title != "" {
		result["title"] = e.Title
	}

	if e.Detail != "" {
		result["detail"] = e.Detail
	}

	if e.Instance != "" {
		result["instance"] = e.Instance
	}

	if e.Code != "" {
		result["code"] = e.Code
	}

	if e.Errors != nil {
		result["errors"] = e.Errors
	}

	return json.Marshal(result)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (e *RFC9457ErrorWithExtensions) UnmarshalJSON(
	data []byte,
) error {
	var baseError RFC9457Error

	err := json.Unmarshal(data, &baseError)
	if err != nil {
		return err
	}

	e.RFC9457Error = baseError

	extensions := map[string]any{}

	err = json.Unmarshal(data, &extensions)
	if err != nil {
		return err
	}

	for _, key := range []string{"type", "status", "title", "detail", "instance", "code", "errors"} {
		delete(extensions, key)
	}

	if e.Detail == "" {
		message, ok := extensions["message"]
		if ok && message != nil {
			msg, ok := message.(string)
			if ok {
				e.Detail = msg
			}

			delete(extensions, "message")
		}
	}

	e.Extensions = extensions

	return nil
}
