// Copyright 2026 RelyChan Pte. Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package httperror defines HTTP error types.
package httperror

import (
	"io"
	"net/http"
	"strconv"
	"strings"
)

// HTTPError is the data structure of an HTTP error
// that follows the [RFC 9457] specification.
// The schema is inspired by [Swagger API] specification.
//
// [RFC 9457]: https://www.rfc-editor.org/rfc/rfc9457.html
// [Swagger API]: https://swagger.io/blog/problem-details-rfc9457-api-error-handling/
type HTTPError struct {
	// A URI reference that identifies the problem type.
	Type string `json:"type,omitempty"`
	// The HTTP status code generated by the origin server for this occurrence of the problem.
	Status int `json:"status,omitempty"`
	// A short, human-readable summary of the problem type.
	Title string `json:"title,omitempty"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.
	// It may or may not yield further information if dereferenced.
	Instance string `json:"instance,omitempty"`
	// An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry.
	Code string `json:"code,omitempty"`
	// An array of error details to accompany a problem details response.
	Errors []ValidationError `json:"errors,omitempty"`
}

// NewHTTPError creates an HTTPError instance with status.
func NewHTTPError(httpStatus int, detail string) *HTTPError {
	return &HTTPError{
		Type:   "about:blank",
		Status: httpStatus,
		Title:  http.StatusText(httpStatus),
		Detail: detail,
	}
}

// ValidationError is an object to provide explicit details on a problem towards an API consumer.
type ValidationError struct {
	// A granular description on the specific error related to a body property, query parameter, path parameters, and/or header.
	Detail string `json:"detail"`
	// A JSON Pointer to a specific request body property that is the source of error.
	Pointer string `json:"pointer,omitempty"`
	// The name of the query or path parameter that is the source of error.
	Parameter string `json:"parameter,omitempty"`
	// The name of the header that is the source of error.
	Header string `json:"header,omitempty"`
	// A string containing additional provider specific codes to identify the error context.
	Code string `json:"code,omitempty"`
	// A hint text to guide how to fix the issue.
	Hint string `json:"hint,omitempty"`
}

// Error implements the error interface for ValidationError.
func (ed ValidationError) Error() string {
	var sb strings.Builder

	sb.Grow(30 +
		len(ed.Pointer) + len(ed.Parameter) + len(ed.Header) +
		len(ed.Code) + len(ed.Hint))

	buildValidationErrorToString(&sb, ed, "")

	return sb.String()
}

// NewAlreadyExistsError creates an error that occurs when the resource being created is found to already exist on the server.
func NewAlreadyExistsError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/already-exists",
		Title:  "Already exists",
		Detail: "The resource being created already exists.",
		Status: http.StatusConflict,
		Code:   "409-01",
		Errors: errors,
	}
}

// NewServiceUnavailableError creates an error that occurs when the service requested is currently unavailable and the server is not ready to handle the request.
// Your client application did everything correct. Unfortunately our API is currently unavailable.
func NewServiceUnavailableError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "about:blank",
		Title:  "Service Unavailable",
		Detail: "The service is currently unavailable.",
		Status: http.StatusServiceUnavailable,
		Code:   "503-01",
		Errors: errors,
	}
}

// NewLicenseCancelledError creates an error that occurs when the license associated with the client has been cancelled thus rendering the service unavailable.
func NewLicenseCancelledError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/license-cancelled",
		Title:  "License Cancelled",
		Detail: "The service is unavailable as the license associated with your client or organization has been cancelled. Please contact your account manager or representative.",
		Status: http.StatusServiceUnavailable,
		Code:   "503-02",
		Errors: errors,
	}
}

// NewLicenseExpiredError creates an error that occurs when the license associated with the client has expired thus rendering the service unavailable.
func NewLicenseExpiredError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/license-expired",
		Title:  "License Expired",
		Detail: "The service is unavailable as the license associated with your client or organization has expired. Please contact your account manager or representative.",
		Status: http.StatusServiceUnavailable,
		Code:   "503-03",
		Errors: errors,
	}
}

// NewNotFoundError creates an error that occurs when the requested resource could not be found.
// Your client application tried to access a resource that does not exist (or could not be found).
// Please review how your users initiated such a request.
func NewNotFoundError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "about:blank",
		Title:  "Not Found",
		Detail: "The requested resource was not found.",
		Status: http.StatusNotFound,
		Code:   "404-01",
		Errors: errors,
	}
}

// NewUnauthorizedError creates an error that occurs when the request lacks valid authentication credentials.
// Your client application tried to access a resource without providing a valid access token or authentication information.
// Please ensure that your requests include the necessary authentication credentials.
func NewUnauthorizedError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "about:blank",
		Title:  "Unauthorized",
		Detail: "Access token not set or invalid, and the requested resource could not be returned.",
		Status: http.StatusUnauthorized,
		Code:   "401-01",
		Errors: errors,
	}
}

// NewForbiddenError creates an error that occurs when the requested resource
// (and/or operation combination) is not authorized for the requesting client (and or authorization context).
// Your client application tried to perform an operation on a resource that
// it’s not authorized to perform in the given context.
func NewForbiddenError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "about:blank",
		Title:  "Forbidden",
		Detail: "The resource could not be returned as the requestor is not authorized.",
		Status: http.StatusForbidden,
		Code:   "403-01",
		Errors: errors,
	}
}

// NewBadRequestError creates an error that occurs when the server cannot or will not process the request
// due to something that is perceived to be a client error
// (for example, malformed request syntax, invalid request message framing, or deceptive request routing).
// Your client application initiated a request that is malformed.
// Please review your client request against the defined semantics for the API.
func NewBadRequestError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "about:blank",
		Title:  "Bad Request",
		Detail: "The request is invalid or malformed.",
		Status: http.StatusBadRequest,
		Code:   "400-01",
		Errors: errors,
	}
}

// NewServerError creates an error that occurs when the server encounters an unexpected condition that prevents it from fulfilling the request.
// Your client application did everything correct. Unfortunately our API encountered a condition that resulted in this problem.
func NewServerError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "about:blank",
		Title:  "Server Error",
		Detail: "The server encountered an unexpected error.",
		Status: http.StatusInternalServerError,
		Code:   "500-01",
		Errors: errors,
	}
}

// NewMissingRequestHeaderError occurs when the request sent to the API is missing an expected request header.
func NewMissingRequestHeaderError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/missing-request-header",
		Title:  "Missing request header",
		Detail: "The request is missing an expected HTTP request header.",
		Status: http.StatusBadRequest,
		Code:   "400-02",
		Errors: errors,
	}
}

// NewMissingRequestParameterError occurs when the request sent to the API is missing a query or path parameter.
func NewMissingRequestParameterError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/missing-request-parameter",
		Title:  "Missing request parameter",
		Detail: "The request is missing an expected query or path parameter.",
		Status: http.StatusBadRequest,
		Code:   "400-03",
		Errors: errors,
	}
}

// NewInvalidBodyPropertyFormatError occurs when the request body contains a malformed property.
func NewInvalidBodyPropertyFormatError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/invalid-body-property-format",
		Title:  "Invalid Body Property Format",
		Detail: "The request body contains a malformed property.",
		Status: http.StatusBadRequest,
		Code:   "400-04",
		Errors: errors,
	}
}

// NewInvalidRequestParameterFormatError occurs when the request contains a malformed query or path parameter.
// Your client issued a request that contained a malformed query or path parameter.
// Please review your request parameters and compare against the shared API definition.
// Consider validating your parameters published schema prior to sending to the server.
func NewInvalidRequestParameterFormatError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/invalid-request-parameter-format",
		Title:  "Invalid Request Parameter Format",
		Detail: "The request contains a malformed query parameter.",
		Status: http.StatusBadRequest,
		Code:   "400-05",
		Errors: errors,
	}
}

// NewInvalidRequestHeaderFormatError occurs when the request contains a malformed request header.
// Your client issued a request that contained a malformed request header.
// Please review your request parameters and compare against the shared API definition when applicable.
// Consider validating your headers against the published schema or API definition metadata prior to sending to the server.
func NewInvalidRequestHeaderFormatError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/invalid-request-header-format",
		Title:  "Invalid Request Header Format",
		Detail: "The request contains a malformed request header parameter.",
		Status: http.StatusBadRequest,
		Code:   "400-06",
		Errors: errors,
	}
}

// NewInvalidBodyPropertyValueError occurs when the request body contains an invalid property value.
func NewInvalidBodyPropertyValueError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/invalid-body-property-value",
		Title:  "Invalid Body Property Value",
		Detail: "The request body contains an invalid body property value.",
		Status: http.StatusBadRequest,
		Code:   "400-07",
		Errors: errors,
	}
}

// NewInvalidRequestParameterValueError occurs when the request contains an invalid query or path parameter value.
func NewInvalidRequestParameterValueError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/invalid-request-parameter-value",
		Title:  "Invalid Request Parameter Value",
		Detail: "The request contains an invalid request parameter value.",
		Status: http.StatusBadRequest,
		Code:   "400-08",
		Errors: errors,
	}
}

// NewMissingBodyPropertyError creates a missing body property error.
// This problem occurs when the request sent to the API is missing an expected body property.
func NewMissingBodyPropertyError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/missing-body-property",
		Title:  "Missing body property",
		Detail: "The request is missing an expected body property.",
		Status: http.StatusBadRequest,
		Code:   "400-09",
		Errors: errors,
	}
}

// NewBusinessRuleViolationError occurs when the request is deemed unprocessable.
// Your client issued a request that failed business rule validation.
// Please review your request to determine if you can remain within appropriate business rules.
// Consider validating your request against available metadata (e.g. schemas) prior to sending to the server.
func NewBusinessRuleViolationError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/business-rule-violation",
		Title:  "Business Rule Violation",
		Detail: "The request body is invalid and not meeting business rules.",
		Status: http.StatusUnprocessableEntity,
		Code:   "422-01",
		Errors: errors,
	}
}

// NewValidationError occurs when the request is deemed unprocessable.
func NewValidationError(errors ...ValidationError) *HTTPError {
	return &HTTPError{
		Type:   "https://problems-registry.smartbear.com/validation-error",
		Title:  "Validation Error",
		Detail: "The request is not valid.",
		Status: http.StatusUnprocessableEntity,
		Code:   "422-02",
		Errors: errors,
	}
}

// NewHTTPErrorFromResponse creates an [HTTPError] from an HTTP response.
func NewHTTPErrorFromResponse(resp *http.Response) *HTTPError {
	if resp == nil {
		return NewServerError()
	}

	respError := NewHTTPError(resp.StatusCode, "")

	switch resp.StatusCode {
	case http.StatusBadRequest:
		respError = NewBadRequestError()
	case http.StatusUnauthorized:
		respError = NewUnauthorizedError()
	case http.StatusForbidden:
		respError = NewForbiddenError()
	case http.StatusNotFound:
		respError = NewNotFoundError()
	case http.StatusInternalServerError:
		respError = NewServerError()
	case http.StatusUnprocessableEntity:
		respError = NewValidationError()
	case http.StatusServiceUnavailable:
		respError = NewServiceUnavailableError()
	default:
	}

	if resp.Request != nil && resp.Request.URL != nil {
		respError.Instance = resp.Request.URL.String()
	}

	if resp.Body != nil {
		const maxErrorBodyBytes int64 = 64 * 1024

		bodyBytes, err := io.ReadAll(io.LimitReader(resp.Body, maxErrorBodyBytes+1))

		_ = resp.Body.Close() //nolint:errcheck

		if err == nil {
			if int64(len(bodyBytes)) > maxErrorBodyBytes {
				respError.Detail = string(bodyBytes[:maxErrorBodyBytes]) + "... (truncated)"
			} else {
				respError.Detail = string(bodyBytes)
			}
		}
	}

	return respError
}

// Error implements the error interface for HTTPError.
func (e HTTPError) Error() string {
	return NewHTTPErrorStringBuilder(e).String()
}

// build the error to debug string with indent format.
func buildValidationErrorToString(
	sb *strings.Builder,
	ed ValidationError,
	prefix string,
) {
	wroteField := false
	writeField := func(name, value string) {
		if value == "" {
			return
		}

		if wroteField {
			sb.WriteByte('\n')
			sb.WriteString(prefix)
		}

		sb.WriteString(name)
		sb.WriteString(": ")
		sb.WriteString(value)

		wroteField = true
	}

	writeField("detail", ed.Detail)
	writeField("code", ed.Code)
	writeField("pointer", ed.Pointer)
	writeField("parameter", ed.Parameter)
	writeField("header", ed.Header)
	writeField("hint", ed.Hint)
}

// NewHTTPErrorStringBuilder creates a string builder from an [HTTPError].
func NewHTTPErrorStringBuilder(e HTTPError) *strings.Builder {
	sb := &strings.Builder{}

	sb.Grow(60 +
		len(e.Title) + len(e.Code) + len(e.Detail) + len(e.Instance) +
		len(e.Type) + (len(e.Errors) * 20))

	wroteField := false
	writeField := func(name, value string) {
		if value == "" {
			return
		}

		if wroteField {
			sb.WriteByte('\n')
		}

		sb.WriteString(name)
		sb.WriteString(": ")
		sb.WriteString(value)

		wroteField = true
	}

	writeField("title", e.Title)
	writeField("type", e.Type)

	if e.Status != 0 {
		if wroteField {
			sb.WriteByte('\n')
		}

		sb.WriteString("status: ")
		sb.WriteString(strconv.Itoa(e.Status))

		wroteField = true
	}

	writeField("instance", e.Instance)
	writeField("detail", e.Detail)

	if len(e.Errors) > 0 {
		if wroteField {
			sb.WriteByte('\n')
		}

		sb.WriteString("errors:")

		for _, ed := range e.Errors {
			sb.WriteString("\n  - ")
			buildValidationErrorToString(sb, ed, "    ")
		}
	}

	return sb
}
